### ISSUE TITLE
Error building main on Windows

### ISSUE THREAD

**Issue by dimastbk** [omerbenamram/pyo3-file#18]
Hi!

`os::std::fd` that was added in https://github.com/omerbenamram/pyo3-file/pull/13, isn't supported on windows.

**Comment by Gentle** [comment]
I ran into the same issue today. With my branch it compiles again on Windows, so I made a PR

https://github.com/omerbenamram/pyo3-file/pull/19

**Comment by omerbenamram** [comment]
Thanks!
